StxFinal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
]

movies/urls.py
from django.urls import path
from movies.views import home, movie_detail, create, update_movies_view

app_name = 'movies'

urlpatterns = [
    path('', home, name="movies-home"),
    path('create/', create, name="create"),
    path('update/', update_movies_view, name="update"),
    path('<movieId>/', movie_detail, name="movie-detail"),
]

movies/models.py
from django.db import models
import datetime


class Movie(models.Model):
    title                   = models.CharField(max_length=60, null=False, blank=False)
    movieId                 = models.IntegerField(unique=True)
    genres                  = models.TextField(max_length=200, null=False, blank=False)
    date                    = models.CharField(max_length=10, null=False, blank=False)
    tags                    = models.TextField(max_length=200, null=False, blank=False, default="")
    ratings                 = models.TextField(max_length=200, null=False, blank=False, default="")

    def __str__(self):
        return self.title

movies/forms.py
from django import forms

class CreateNewMovie(forms.Form):
    movieId = forms.IntegerField()
    title = forms.CharField(max_length=60)
    genres = forms.CharField(max_length=200)
    date = forms.CharField()

class UpdateDb(forms.Form):
    source = forms.CharField(max_length=60)

movies/views.py
from django.shortcuts import render, redirect
from movies.models import Movie
from movies.forms import CreateNewMovie, UpdateDb
from .filters import MovieFilter
import csv, io, requests, zipfile, shutil, os

import io, csv
from django.core.paginator import Paginator

def home(request):
     year = request.GET.get('year')
     if(year):
        movie_items = Movie.objects.filter(date=year)
     else:
        movie_items = Movie.objects.all()

     myFilter = MovieFilter(request.GET, queryset=movie_items)
     movie_items = myFilter.qs

     sort = 'id'
     sort = request.GET.get('sort')
     if sort != None:
         movie_items = Movie.objects.order_by(sort)

     paginator = Paginator(movie_items, 20)
     page = request.GET.get('page')
     movie_items = paginator.get_page(page)

     context = {
            'movie_items': movie_items,
            'myFilter': myFilter,
        }
     return render(request, 'movies/home.html', context)


#SHOW SPECIFIC OBJECT
def movie_detail(request, movieId):
    movie_items = Movie.objects.filter(movieId=movieId)
    for movie_item in movie_items:
        list = movie_item.ratings.split(',')
        list_length = len(list)
        sum = 0.0
        for item in list:
            if item != "":
                sum += float(item)
        rating = round(sum/list_length, 2)
    context = {
        'movie_items': movie_items,
        'rating': rating,
    }
    return render(request, 'movies/detail.html', context)

#USE FORM TO CREATE NEW MOVIE OBJECT
def create(request):
    if request.method == "POST":
        form = CreateNewMovie(request.POST)

        if form.is_valid():
            i = form.cleaned_data['movieId']
            t = form.cleaned_data['title']
            g = form.cleaned_data['genres']
            d = form.cleaned_data['date']

            m = Movie(movieId=i, title=t, genres=g, date=d)
            m.save()
        return redirect("/movies/" + str(m.movieId))
    else:
        form = CreateNewMovie()
    context = {
        'form': form
    }
    return render(request, 'movies/create.html', context)

def update_movies_view(request):
    if request.method == "POST":
        form = UpdateDb(request.POST)
        if form.is_valid():
            s = form.cleaned_data['source']
            #DELETES CSV FOLDER
            if(s == 'ml-latest-small' and os.path.isdir('ml-latest-small')):
                shutil.rmtree('ml-latest-small')
                #DELETE MOVIE OBJECTS FROM DB
                to_delete = Movie.objects.all()
                to_delete.delete()

            #OPEN & EXTRACT ZIP MOVIES
            r = requests.get('http://files.grouplens.org/datasets/movielens/ml-latest-small.zip')
            z = zipfile.ZipFile(io.BytesIO(r.content))
            z.extractall()

            #OPEN CSV MOVIES AND WRITE IT DO DB
            csv_name = open('ml-latest-small/movies.csv', "r")
            with open('ml-latest-small/movies.csv', 'r', encoding="utf8") as csv_file:
                csv_reader = csv.reader(csv_file)
                header = next(csv_reader)
                for line in csv_reader:
                    year = line[1]
                    year = year[-5:-1]
                    if year.isdigit():
                        year = int(year)
                    instance = Movie(movieId=line[0], title =line[1], genres=line[2], date=year)
                    instance.save()

            with open('ml-latest-small/tags.csv', 'r', encoding="utf8") as csv_file:
                csv_reader = csv.reader(csv_file)
                header = next(csv_reader)
                for line in csv_reader:
                    movieId = line[1]
                    tag = line[2]
                    item = Movie.objects.get(movieId=movieId)
                    item.tags += (tag + '|')
                    item.save()

            with open('ml-latest-small/ratings.csv', 'r', encoding="utf8") as csv_file:
                csv_reader = csv.reader(csv_file)
                header = next(csv_reader)
                for line in csv_reader:
                    movieId = line[1]
                    rating = line[2]
                    item = Movie.objects.get(movieId=movieId)
                    item.ratings += (rating + ',')
                    item.save()


    else:
        form = UpdateDb()

    context = {
        'form': form
        }
    return render(request, 'movies/update.html', context)

movies/templates/movies/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
    <nav class="nav nav-tabs">
      <li class="nav-item"><a href="{% url 'movies:movies-home' %}" class="nav-link" >Movie List</a></li>
      <li class="nav-item"><a href="{% url 'movies:update' %}" class="nav-link" >
          <button type="submit" name="button">Update Movie List</button>
      </a></li>
      <li class="nav-item"><a href="{% url 'movies:create' %}" class="nav-link" >Create Movie Item</a></li>
    </nav>

    {% block content %}
    {% endblock content %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

movies/templates/movies/create.html
{% extends 'movies/base.html' %}

{% block content %}
<h2>Create new movie</h2>
<form class="" method="post">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit" name="save">Create new</button>
</form>
{% endblock %}

movies/templates/movies/detail.html
{% extends 'movies/base.html' %}

{% block content %}
<div class="container">
  <div class="row">
      <div class="col-md-11 offset-md-1">
        {% for movie_item in movie_items %}
          <h4>{{movie_item.movieId}} | {{movie_item.title}} Genres: {{movie_item.genres}} Tags: {{movie_item.tags}} Rating: {{rating}}</h4>
        {% endfor %}
      </div>
  </div>

</div>

{% endblock %}

movies/templates/movies/home.html
{% extends 'movies/base.html' %}

{% block content %}
<!-- Movie List -->
<div class="container">
  <!--FILTERING-->
  <div class="row">
    <form method="get">
        {{myFilter.form}}
      <button type="submit" name="button">Filter</button>
    </form>
  </div>
  <!--FILTERING END-->
  <!--SORTING-->
  <div class="row">
    <form method="get">
      <input type="text" name="sort" value="">
      <button type="submit">Sort By</button>
    </form>
  </div>
  <!--SORTING END-->
  <div class="row">
    <div class="">
      {% for movie_item in movie_items %}
        <div class="movie-item-container">
          {% include 'movies/snippets/movie_snippet.html' with movie_item=movie_item %}
        </div>
      {% endfor %}
      <!--PAGINATION-->
      <nav aria-label="Page navigation example">
        <ul class="pagination">
          {% if movie_items.has_previous %}
            <li class="page-item"><a class="page-link" href="?page=1">First Page</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ movie_items.previous_page_number }}">Previous Page</a></li>
          {% endif %}
          {% for num in movie_items.paginator.page_range %}
            {% if movie_items.number == num %}
              <li class="page-item"><a class="page-link" href="">{{num}}</a></li>
            {% elif num > movie_item.number|add:'-3' and num < movie_item.number|add:'3' %}
              <li class="page-item"><a class="page-link" href="">{{num}}</a></li>
            {% endif %}
          {% endfor %}
          {% if movie_items.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ movie_items.next_page_number }}">Next Page</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ movie_items.paginator.num_pages }}">Last Page</a></li>
          {% endif %}
        </ul>
      </nav>
        <!--PAGINATION END-->
    </div>

  </div>

  <div class="row">
    <h4>Movie REST API</h4>
    <h6>Na podstawie danych znajdujących się na stronie https://grouplens.org/datasets/movielens/ (polecamy wykorzystać najmniejszay dataset
      http://files.grouplens.org/datasets/movielens/ml-latest-small.zip)
      należy zaprojektować i stworzyć aplikację w wybranym przez siebie frameworku, która będzie posiadała proste REST API:</h6>
    <p>GET /movies/ - lista wszystkich filmów (widok powinien pozwalać na filtrowanie, sortowanie po roku produkcji filmu przykład : /movies/?year=1995,
      /movies/?sort=-year )
    <br>GET /movies?tag=funny&tag=animation - lista filmów otaggowanych jako "funny" ORAZ "animation"
    <br>GET /movie/<movieId>/ - wybrany film {"title": "Tytuł", "score": 5.1, 'genres’: [Comedy], 'link’: 'link do imdb’, 'year’: 2001}
    <br>POST /db z body {"source": "ml-latest-small"}
    powinno wyczyścić bazę danych
    ściągnąć data set z movielens
    wrzucić do bazy danych wpisy z pobranego data setu.</p>

  </div>

</div>
<!-- END Movie List -->
{% endblock content %}

movies/templates/movies/snippets/movie_snippet.html
<div class="container">
  <div class="row">
      <div class="col-md-11 offset-md-1">
        <a href="/movies/{{movie_item.movieId}}"><h4>{{movie_item.movieId}} | {{movie_item.title}} Genres: {{movie_item.genres}} Tags: {{movie_item.tags}}</h4></a>
      </div>
  </div>

</div>

movies/templates/movies/update.html
{% extends 'movies/base.html' %}

{% block content %}
<h2>Source is ml-latest-small. It may take a while. Qouple of minutes probably :)</h2>
<form class="" action="" method="post">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit" name="save">Update DB</button>
</form>
{% endblock %}